export const ErrorMessages = {
  NoCrust: "MUST USE DOUGH FOR CRUST",
  NoDuplicates:
    "CANNOT CREATE DUPLICATE OF EXISTING PIZZA, PLEASE CHANGE CUSTOMER NAME TO ACCOMODATE",
  NoCustomer: "NO CUSTOMER NAME CREATED",
  NoIngredients:
    "ATTEMPTING TO SAVE PIZZA WITHOUT INGREDIENTS, PLEASE ADD INGREDIENTS OR USE THE DELETE KEY",
};
