export const ErrorMessages = {
  NoCrust: "MUST USE DOUGH FOR CRUST",
  NoDuplicates:
    "CANNOT CREATE DUPLICATE OF EXISTING PIZZA, CHECK THAT CUSTOMER NAME AND ORDER DOESN'T MATCH EXISTING ORDER",
  NoDuplicateNames:
    "PLEASE UPDATE THE CUSTOMER NAME AS IT MATCHES AN EXISTING ORDER",
  NoCustomer: "NO CUSTOMER NAME CREATED",
  NoIngredients:
    "ATTEMPTING TO SAVE PIZZA WITHOUT INGREDIENTS, PLEASE ADD INGREDIENTS OR USE THE DELETE KEY",
  NoDough: "OUT OF CRUST DOUGH, REACH OUT TO MANAGER TO ADD MORE TO INVENTORY",
};
